[registries.crates-io]
protocol = "sparse"

[expand]
theme = "Monokai Extended"

[target."armv6k-nintendo-3ds"]
# runner = "/Users/ianchamberlain/Applications/Citra/nightly/citra"
# runner = [
#     "docker",
#     "run",
#     "-v",
#     "./target:/app/target",
#     "test-runner-3ds:latest",
# ]
[alias]
# would be nice to make this default even for `cargo check` fully spelled out:
c = "check --all-targets"
cl = "clippy --all-targets"
rr = "run --release"
i = "install --locked"

w = "watch -w src,crates --command run --clear"

# This works slightly better than cargo-alias, but also only works on nightly :(
aliases = "-Zunstable-options config get alias"
