[registries.crates-io]
protocol = "sparse"

[expand]
theme = "Monokai Extended"

[alias]
c = "check --all-targets"
cl = "clippy --all-targets --target-dir=target/clippy"
rr = "run --release"
i = "install --locked"

# This works slightly better than cargo-alias, but also only works on nightly :(
# `cargo --list | grep alias` also works for a quick+dirty option
aliases = "-Zunstable-options config get alias"
