#!/bin/bash

# see the look-aside wiki page for details

set -e

WAIT_CMD="read"
DETACHED="-d"
ALWAYS_WAIT=""
RESET=1
if [ "$1" == "-w" ] || [ "$1" == "--wait" ]
then
    echo "Tmux session will stay open after build completes"
    WAIT_CMD=":"
    ALWAYS_WAIT="read"
    shift
elif [ "$1" == "-R" ] || [ "$1" == "--no-reset" ]
then
    echo "Will remain attached, not running greset"
    RESET=0
    DETACHED=""
    shift
fi

LOCAL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $LOCAL_DIR/rgit_utilities.sh

arguments="$@"
rgit_push "Invoking 'build $arguments' on the remote: $RHOST"\
    "bash -lc \"tmux new $DETACHED 'if ! build $arguments; then $WAIT_CMD; fi; $ALWAYS_WAIT'\""

if [ "$RESET" == "1" ]
then
    greset
    tmux_attach
fi
