#!/usr/bin/env bash

# Ensure yadm alt SSH config files are set with the right permissions.
# This might be good as a smudge filter or post-checkout hook or something, idk
chmod go-rw ~/.ssh/*
chmod go+r  ~/.ssh/*.pub*
chmod go-rw ~/.config/yadm/alt/.ssh/*
chmod go+r  ~/.config/yadm/alt/.ssh/*.pub*
