[registries.crates-io]
protocol = "sparse"

[expand]
theme = "Monokai Extended"

[target."armv6k-nintendo-3ds"]
runner = "/Users/ianchamberlain/Applications/Citra/nightly/citra"
# runner = [
#     "docker",
#     "run",
#     "-v",
#     "./target:/app/target",
#     "test-runner-3ds:latest",
# ]
