[registries.crates-io]
protocol = "sparse"

[expand]
theme = "Monokai Extended"

[target."armv6k-nintendo-3ds"]
runner = [
    "docker",
    "run",
    "-v",
    "./target:/app/target",
    "citra-runner:latest",
]
